#!/bin/sh

# READY

# FreeBSD
#   Jails
#       Other OS
#           Not used
#               Abandoned

PROJECTS="
apache-config-freebsd
                                                                            btfc
                                                                            btfc2
btfs
                                                                            checkmail-ahk
crontabbed
        crossdj-mappings
delugefs
deploy
    dillinger
                                                                            dmenu
        doc
    dtfc
                                                                            dwm
                                                                            dwmsd
    echoplexus
                                                                            eza
ffmpeg-tools
freebsd-install-script
freebsd-pf-script
freebsd-ports-test
freebsd-sortconf
freebsd-system-info
github-backup
                                                                            gtfc
    h5ai
hddid
iocage-tools
    kanso-chat
    kanso-example
    kanso-focus
    kanso-manage-couchdb
    kanso-movies
    kanso-music
    kanso-photos
    kanso-wiki
    kanso-wtfc
    klaus
                                                                            kurz.go
    mdwiki
                                                                            mfsbsd
        mixxx-novation-launchpad
mount_iso
netconn
newsyslog.conf.d
nginx-config-sites-enabled
ori-tools
                                                                            Pico
psnap
pwgen
        python-rtmidi
rad
randomword
rsync-tools
setproxy
skel
ssh-multi
ssh-tools
        tf2-config
    transfer.sh
    upload.sh
vmrc
        windows-setup
                                                                            wtfc
zfs-tools
zsnapple
"

# couchdbtodomvc
# couchdb-fuse
# johnko.github.io
# mac-dotfiles

export PROJECTS
