#!/bin/sh

# READY

# FreeBSD
#   Jails
#       Other OS
#           Not used
#               Abandoned

PROJECTS="
apache-config-freebsd       ${REPOSRC}/apache-config-freebsd.git
                                                                            btfc                        ${REPOSRC}/btfc.git
                                                                            btfc2                       ${REPOSRC}/btfc2.git
btfs                        ${REPOSRC}/btfs.git
                                                                            checkmail-ahk               ${REPOSRC}/checkmail-ahk.git
crontabbed                  ${REPOSRC}/crontabbed.git
        crossdj-mappings            ${REPOSRC}/crossdj-mappings.git
delugefs                    ${REPOSRC}/delugefs.git
deploy                      ${REPOSRC}/deploy.git
    dillinger                   ${REPOSRC}/dillinger.git
                                                                            dmenu                       ${REPOSRC}/dmenu.git
        doc                         ${REPOSRC}/doc.git
    dtfc                        ${REPOSRC}/dtfc.git
                                                                            dwm                         ${REPOSRC}/dwm.git
                                                                            dwmsd                       ${REPOSRC}/dwmsd.git
    echoplexus                  ${REPOSRC}/echoplexus.git
                                                                            eza                         ${REPOSRC}/eza.git
ffmpeg-tools                ${REPOSRC}/ffmpeg-tools.git
freebsd-install-script      ${REPOSRC}/freebsd-install-script.git
freebsd-pf-script           ${REPOSRC}/freebsd-pf-script.git
freebsd-ports-test          ${REPOSRC}/freebsd-ports-test.git
freebsd-sortconf            ${REPOSRC}/freebsd-sortconf.git
freebsd-system-info         ${REPOSRC}/freebsd-system-info.git
github-backup               ${REPOSRC}/github-backup.git
                                                                            gtfc                        ${REPOSRC}/gtfc.git
    h5ai                        ${REPOSRC}/h5ai.git
hddid                       ${REPOSRC}/hddid.git
iocage-tools                ${REPOSRC}/iocage-tools.git
    kanso-chat                  ${REPOSRC}/kanso-chat.git
    kanso-example               ${REPOSRC}/kanso-example.git
    kanso-focus                 ${REPOSRC}/kanso-focus.git
    kanso-manage-couchdb        ${REPOSRC}/kanso-manage-couchdb.git
    kanso-movies                ${REPOSRC}/kanso-movies.git
    kanso-music                 ${REPOSRC}/kanso-music.git
    kanso-photos                ${REPOSRC}/kanso-photos.git
    kanso-wiki                  ${REPOSRC}/kanso-wiki.git
    kanso-wtfc                  ${REPOSRC}/kanso-wtfc.git
    klaus                       ${REPOSRC}/klaus.git
                                                                            kurz.go                     ${REPOSRC}/kurz.go.git
    mdwiki                      ${REPOSRC}/mdwiki.git
                                                                            mfsbsd                      ${REPOSRC}/mfsbsd.git
        mixxx-novation-launchpad    ${REPOSRC}/mixxx-novation-launchpad.git
mount_iso                   ${REPOSRC}/mount_iso.git
netconn                     ${REPOSRC}/netconn.git
newsyslog.conf.d            ${REPOSRC}/newsyslog.conf.d.git
nginx-config-sites-enabled  ${REPOSRC}/nginx-config-sites-enabled.git
                                                                            Pico                        ${REPOSRC}/Pico.git
psnap                       ${REPOSRC}/psnap.git
pwgen                       ${REPOSRC}/pwgen.git
        python-rtmidi               ${REPOSRC}/python-rtmidi.git
rad                         ${REPOSRC}/rad.git
randomword                  ${REPOSRC}/randomword.git
rsync-tools                 ${REPOSRC}/rsync-tools.git
setproxy                    ${REPOSRC}/setproxy.git
skel                        ${REPOSRC}/skel.git
ssh-multi                   ${REPOSRC}/ssh-multi.git
ssh-tools                   ${REPOSRC}/ssh-tools.git
        tf2-config                  ${REPOSRC}/tf2-config.git
    transfer.sh                 ${REPOSRC}/transfer.sh.git
    upload.sh                   ${REPOSRC}/upload.sh.git
vmrc                        ${REPOSRC}/vmrc.git
        windows-setup               ${REPOSRC}/windows-setup.git
                                                                            wtfc                        ${REPOSRC}/wtfc.git
zfs-tools                   ${REPOSRC}/zfs-tools.git
zsnapple                    ${REPOSRC}/zsnapple.git
"

# ${REPOSRC}/couchdbtodomvc.git
# ${REPOSRC}/couchdb-fuse.git
# ${REPOSRC}/johnko.github.io.git
# ${REPOSRC}/mac-dotfiles.git

export PROJECTS
