#!/bin/sh

# Usage: $0 [create|github|home]

FOLDER="${HOME}/github"
ACTION=$1

if [ "x" == "x${FQDN}" ]; then
    echo "Please set or export variable FQDN"
    exit 1
fi

#if [ "x" == "x${TOKEN}" ]; then
#    echo "Please set or export variable TOKEN"
#    exit 1
#fi

if [ "x" == "x${REPOSRC}" ]; then
    REPOSRC=https://github.com/johnko
fi

. ${0%/*}/git_conf

if [ "x" == "x${PROJECTS}" ]; then
    echo "Can't load git_conf"
    exit 1
fi

echo "${PROJECTS}" \
| while read name ; do
    if [ "x" != "x${name}" ]; then
        echo "${name}"
        if [ ! -e "${FOLDER}/johnko/${name}" ]; then
            mkdir -p "${FOLDER}/johnko"
            git clone ${REPOSRC}/${name} "${FOLDER}/johnko/${name}"
            cd "${FOLDER}/johnko/${name}"
            git remote rename origin github
            if git remote -v | grep "github.com/johnko" ; then
                # use ssh
                git remote set-url github "git@github.com:johnko/${name##*/}.git"
            fi
        else
            cd "${FOLDER}/johnko/${name}"
#            git remote remove home
            if ! git remote -v | grep "^home" > /dev/null ; then
                git remote add home ssh://git@${FQDN}:23/usr/local/git/repos/${name}
            elif ! git remote -v | grep "^home" | grep "usr/local/git/repos" > /dev/null ; then
                git remote set-url home ssh://git@${FQDN}:23/usr/local/git/repos/${name}
            fi
        fi
        if [ "xgithub" == "x${ACTION}" ]; then
            cd "${FOLDER}/johnko/${name}"
            if git remote -v | grep "github.com:johnko" ; then
                git push --mirror github
            fi
        fi
        if [ "xhome" == "x${ACTION}" ]; then
            cd "${FOLDER}/johnko/${name}"
            if git remote -v | grep "git@${FQDN}:23/usr/local/git/repos/${name}" ; then
                git push --mirror home
            fi
        fi
    fi
done
