#!/bin/sh

######################################################################
# Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
######################################################################
SCRIPTVERSION=150725-042212

# Usage: $0 [create|github|home]

FOLDER="/tank/dlna/git"
ACTION=$1

if [ "x" == "x${FQDN}" ]; then
    echo "Please set or export variable FQDN"
    exit 1
fi

if [ "x" == "x${TOKEN}" ]; then
    echo "Please set or export variable TOKEN"
    exit 1
fi

if [ "x" == "x${REPOSRC}" ]; then
    REPOSRC=https://github.com/
fi

if [ "x" == "x${GITLABSRC}" ]; then
    GITLABSRC=https://gitlab.com/
fi

. ${0%/*}/git_conf

if [ "x" == "x${PROJECTS}" ]; then
    echo "Can't load git_conf"
    exit 1
fi

groups() {
    echo "${PROJECTS}" \
    | while read name url ; do
        if [ "x" != "x${name}" ] && [ "x" != "x${url}" ]; then
            echo "${url}" | sed -E 's;https?://[^/][^/]*/;v.;g' | sed -E 's;/.*;;g'
        fi
    done
}

if [ "xcreate" == "x${ACTION}" ]; then
    for name in `groups | sort -u` ; do
        if [ "x" != "x${name}" ]; then
            curl \
            --header "PRIVATE-TOKEN: ${TOKEN}" \
            -X POST \
            -d "name=${name}&path=${name}" "https://${FQDN}/api/v3/groups"
        fi
    done
fi

echo "${PROJECTS}" \
| while read name url ; do
    if [ "x" != "x${name}" ] && [ "x" != "x${url}" ]; then
        groupname=`echo "${url}" | sed -E 's;https?://[^/][^/]*/;v.;g' | sed -E 's;/.*;;g'`
        echo "${groupname}/${name}"
        if [ "xcreate" == "x${ACTION}" ]; then
            if ! curl -s --head "https://${FQDN}/${groupname}/${name}" | grep '200 OK' ; then
                projectid=`curl -s --header "PRIVATE-TOKEN: ${TOKEN}" \
                    -X POST -d "user_id=root&name=${name}&public=true" \
                    "https://${FQDN}/api/v3/projects" \
                    | grep -o '"id" *: *[0-9][0-9]* *,' | head -1 | grep -o '[0-9][0-9]*'`
                groupid=`curl -s --header "PRIVATE-TOKEN: ${TOKEN}" \
                    "https://${FQDN}/api/v3/groups" \
                    | grep -o "\"id\" *: *[0-9][0-9]* *, *\"name\" *: *\"${groupname}\"" | head -1 | grep -o '[0-9][0-9]*' | head -1`
                echo
                echo "==== Transferring ${name} to ${groupname}: https://${FQDN}/api/v3/groups/${groupid}/projects/${projectid}"
                while curl -s --header "PRIVATE-TOKEN: ${TOKEN}" \
                    -X POST \
                    "https://${FQDN}/api/v3/groups/${groupid}/projects/${projectid}" | grep 'Cannot move project' ; do
                        sleep 20
                done
            fi
        fi
        novgroupname=`echo "${url}" | sed -E 's;https?://[^/][^/]*/;;g' | sed -E 's;/.*;;g'`
             urlpath=`echo "${url}" | sed -E 's;https?://[^/][^/]*/;;g'`
        if [ ! -e "${FOLDER}/${novgroupname}/${name}" ]; then
            mkdir -p "${FOLDER}/${novgroupname}"
            git clone ${url} "${FOLDER}/${novgroupname}/${name}"
            cd "${FOLDER}/${novgroupname}/${name}"
            git remote rename origin github
            if git remote -v | grep "github.com/johnko" ; then
                # use ssh
                git remote set-url github "git@github.com:johnko/${i##*/}.git"
            fi
        else
            cd "${FOLDER}/${novgroupname}/${name}"
#            git remote remove home
            if ! git remote -v | grep "^home" > /dev/null ; then
                git remote add home ssh://git@${FQDN}:23/v.${urlpath}
            fi
        fi
        if [ "xgithub" == "x${ACTION}" ]; then
            cd "${FOLDER}/${novgroupname}/${name}"
            if git remote -v | grep "github.com:johnko" ; then
                git push --mirror github
            fi
        fi
        if [ "xhome" == "x${ACTION}" ]; then
            cd "${FOLDER}/${novgroupname}/${name}"
            if git remote -v | grep "git@${FQDN}:23/v.${urlpath}" ; then
                git push --mirror home
            fi
        fi
    fi
done
