#!/bin/sh

######################################################################
# Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
######################################################################
SCRIPTVERSION=150707-001642

if [ "x" == "x${FQDN}" ]; then
    echo "Please set or export variable FQDN"
    exit 1
fi

if [ "x" == "x${TOKEN}" ]; then
    echo "Please set or export variable TOKEN"
    exit 1
fi

if [ "x" == "x${REPOSRC}" ]; then
    REPOSRC=https://github.com/
fi

if [ "x" == "x${GITLABSRC}" ]; then
    GITLABSRC=https://gitlab.com/
fi

PROJECTS="
    apache-config-freebsd       ${REPOSRC}johnko/apache-config-freebsd.git
    btfc2                       ${REPOSRC}johnko/btfc2.git
    crontabbed                  ${REPOSRC}johnko/crontabbed.git
    deploy                      ${REPOSRC}johnko/deploy.git
    eza                         ${REPOSRC}johnko/eza.git
    freebsd-install-script      ${REPOSRC}johnko/freebsd-install-script.git
    freebsd-pf-script           ${REPOSRC}johnko/freebsd-pf-script.git
    freebsd-sortconf            ${REPOSRC}johnko/freebsd-sortconf.git
    freebsd-system-info         ${REPOSRC}johnko/freebsd-system-info.git
    github-backup               ${REPOSRC}johnko/github-backup.git
    gtfc                        ${REPOSRC}johnko/gtfc.git
    hddid                       ${REPOSRC}johnko/hddid.git
    mount_iso                   ${REPOSRC}johnko/mount_iso.git
    netconn                     ${REPOSRC}johnko/netconn.git
    nginx-config-sites-enabled  ${REPOSRC}johnko/nginx-config-sites-enabled.git
    psnap                       ${REPOSRC}johnko/psnap.git
    pwgen                       ${REPOSRC}johnko/pwgen.git
    randomword                  ${REPOSRC}johnko/randomword.git
    setproxy                    ${REPOSRC}johnko/setproxy.git
    ssh-multi                   ${REPOSRC}johnko/ssh-multi.git
    ssh-tools                   ${REPOSRC}johnko/ssh-tools.git
    zsnapple                    ${REPOSRC}johnko/zsnapple.git
    skel                        ${REPOSRC}johnko/skel.git
    dtfc                        ${REPOSRC}johnko/dtfc.git
    echoplexus                  ${REPOSRC}johnko/echoplexus.git
    gitlab-ce                   ${GITLABSRC}gitlab-org/gitlab-ce.git
"

groups() {
    echo "${PROJECTS}" \
    | while read name url ; do
        if [ "x" != "x${name}" ] && [ "x" != "x${url}" ]; then
            echo "${url}" | sed -E 's;https?://[^/][^/]*/;v.;g' | sed -E 's;/.*;;g'
        fi
    done
}

for name in `groups | sort -u` ; do
    if [ "x" != "x${name}" ]; then
        curl \
        --header "PRIVATE-TOKEN: ${TOKEN}" \
        -X POST \
        -d "name=${name}&path=${name}" "https://${FQDN}/api/v3/groups"
    fi
done

echo "${PROJECTS}" \
| while read name url ; do
    if [ "x" != "x${name}" ] && [ "x" != "x${url}" ]; then
        groupname=`echo "${url}" | sed -E 's;https?://[^/][^/]*/;v.;g' | sed -E 's;/.*;;g'`
        if ! curl -s --header "PRIVATE-TOKEN: ${TOKEN}" "https://${FQDN}/api/v3/projects" | grep -o "${groupname}/${name}" ; then
            projectid=`curl -s --header "PRIVATE-TOKEN: ${TOKEN}" \
                -X POST -d "user_id=root&name=${name}&public=true&import_url=${url}" \
                "https://${FQDN}/api/v3/projects" \
                | grep -o '"id" *: *[0-9][0-9]* *,' | head -1 | grep -o '[0-9][0-9]*'`
            groupid=`curl -s --header "PRIVATE-TOKEN: ${TOKEN}" \
                "https://${FQDN}/api/v3/groups" \
                | grep -o "\"id\" *: *[0-9][0-9]* *, *\"name\" *: *\"${groupname}\"" | head -1 | grep -o '[0-9][0-9]*' | head -1`
            echo
            echo "==== Transferring ${name} to ${groupname}: https://${FQDN}/api/v3/groups/${groupid}/projects/${projectid}"
            while curl -s --header "PRIVATE-TOKEN: ${TOKEN}" \
                -X POST \
                "https://${FQDN}/api/v3/groups/${groupid}/projects/${projectid}" | grep 'Cannot move project' ; do
                    sleep 20
            done
        fi
    fi
done
