#!/bin/sh
name=${1}
FQDN=${2}
couchdatabases="movies music wiki"
otherslashes="couch dtfc piwik owncloud zabbix"
gitlabpaths="admin assets dashboard explore groups help profile projects s search snippets u users"
tlsconf="/usr/local/etc/nginx/tls.conf"
proxypass="/usr/local/etc/nginx/proxypass.conf"
cat >/usr/jails/${name}/usr/local/etc/nginx/sites-enabled/${name} <<EOF
client_max_body_size 0;
upstream couchsources {
    server ${IPNET}`jailip couch`:5984;
}
upstream dtfcsources {
    server ${IPNET}`jailip dtfc`:8080;
}
upstream piwiksources {
    server ${IPNET}`jailip piwik`:443;
}
upstream owncloudsources {
    server ${IPNET}`jailip owncloud`:443;
}
upstream gitlabsources {
    server ${IPNET}`jailip gitlab`:443;
}
upstream zabbixsources {
    server ${IPNET}`jailip zabbix`:443;
}
map \$uri \$redirect_uri {
EOF
for c in ${couchdatabases} ${otherslashes} ; do
    cat >>/usr/jails/${name}/usr/local/etc/nginx/sites-enabled/${name} <<EOF
    ~^/${c}\$   https://${FQDN}/${c}/;
EOF
done
cat >>/usr/jails/${name}/usr/local/etc/nginx/sites-enabled/${name} <<EOF
    ~^/\$         https://${FQDN}/explore;
}
server {
    listen   ${IPNET}`jailip nginx`:80 default_server;
    server_name ${FQDN};
    server_name ${IPNET}`jailip nginx`;
    return 302 https://\$host\$request_uri;
}
server {
    listen 443 ssl;
    server_name ${FQDN};
    ssl_certificate ssl/ssl.crt;
    ssl_certificate_key ssl/ssl.key;
    include ${tlsconf};
    location ~^/(_session|_replicate|_users) {
        rewrite  /(.*) /\$1 break;
        include ${proxypass};
        proxy_pass http://couchsources;
    }
    location ~^/couch/ {
        rewrite  /couch/(.*) /\$1 break;
        include ${proxypass};
        proxy_pass http://couchsources;
    }
    location  ~^/dtfc/ {
        rewrite /dtfc/(.*) /\$1 break;
        include ${proxypass};
        proxy_pass http://dtfcsources;
    }
    location  ~^/piwik/ {
        rewrite /piwik/(.*) /piwik/\$1 break;
        include ${proxypass};
        proxy_pass https://piwiksources;
    }
    location  ~^/owncloud/ {
        rewrite /owncloud/(.*) /owncloud/\$1 break;
        include ${proxypass};
        proxy_pass https://owncloudsources;
    }
    location  ~^/zabbix/ {
        rewrite /zabbix/(.*) /zabbix/\$1 break;
        include ${proxypass};
        proxy_pass https://zabbixsources;
    }
    location / {
        try_files \$uri \$uri/ @redirect-map;
    }
    location @redirect-map {
        if (\$redirect_uri) {
            return 302 \$redirect_uri;
        }
    }
EOF
for c in ${couchdatabases} ; do
    cat >>/usr/jails/${name}/usr/local/etc/nginx/sites-enabled/${name} <<EOF
    location  ~^/${c}/ {
        rewrite /${c}/(.*) /${c}/_design/${c}/_rewrite/\$1 break;
        include ${proxypass};
        proxy_pass http://couchsources;
    }
EOF
done
for g in ${gitlabpaths} ; do
    cat >>/usr/jails/${name}/usr/local/etc/nginx/sites-enabled/${name} <<EOF
    location  ~^/${g}/ {
        rewrite /${g}/(.*) /${g}/\$1 break;
        include ${proxypass};
        proxy_pass http://gitlabsources;
    }
    location  ~^/${g}\$ {
        rewrite /${g} /${g} break;
        include ${proxypass};
        proxy_pass http://gitlabsources;
    }
EOF
done
cat >>/usr/jails/${name}/usr/local/etc/nginx/sites-enabled/${name} <<EOF
#letfover slashes or more to gitlab
location  ~^/(.*)/(.*) {
    rewrite /(.*)/(.*) /\$1/\$2 break;
    include ${proxypass};
    proxy_pass http://gitlabsources;
}
}
EOF
} # end of setupnginxconfig
